@devUrl = http://localhost:3000
@prodUrl = http://localhost:3000
@host = {{devUrl}}

### Create a new user
POST {{host}}/auth/signup
content-type: application/json

{
  "email": "kano@nrs.com",
  "password": "wherekane"
}

### signin user
POST {{host}}/auth/signin
content-type: application/json

{
  "email": "kano@nrs.com",
  "password": "wherekane"
}

### signout user
POST {{host}}/auth/signout
content-type: application/json

### who am I
GET {{host}}/auth/whoami
content-type: application/json


### find user by id
GET {{host}}/auth/1
content-type: application/json

### find user by email
GET {{host}}/auth?email=subzero@nrs.com
content-type: application/json

### delete user by id
DELETE {{host}}/auth/2

### Update an user
PATCH {{host}}/auth/3
content-type: application/json

{
  "email": "cybersubzero@nrs.com"
}